# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: 'ACR secrets'

trigger:
- master

pr:
- master

steps:
- script: ./run-tests.sh

- script: |
    docker build -t $(ACRUserName).azurecr.io/time-recorder/server:$(Build.BuildNumber) server
    docker login -u $(ACRUserName) -p $(ACRPassword) $(ACRLoginServer)
    docker push $(ACRUserName).azurecr.io/time-recorder/server:$(Build.BuildNumber)
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
