# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: 'ACR secrets'

trigger:
- master

pr:
- master

steps:
- script: |
    # dotnet restore
    # dotnet test server/ActivityTracker.Server.sln --no-restore --logger trx
    # docker build -t temp server
    echo docker login -u $(ACRUserName) -p $(ACRPassword) $(ACRLoginServer)
    echo docker push $(ACRUserName).azurecr.io/time-recorder:$(Build.BuildNumber)
  failOnStderr: true
    
- script: |
    docker build -t $(ACRUserName).azurecr.io/time-recorder:$(Build.BuildNumber) server
    docker login -u $(ACRUserName) -p $(ACRPassword) $(ACRLoginServer)
    docker push $(ACRUserName).azurecr.io/time-recorder:$(Build.BuildNumber)
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  failOnStderr: true
    
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'